export { default as Clients } from "./Clients/Clients";
export { default as Dash } from "./Dash/Dash";
export { default as DesingModels } from "./DesingModels/DesingModels";
export { default as Finances } from "./Finances/Finances";
export { default as GitHubGestion } from "./GitHubGestion/GitHubGestion";
export { default as Projects } from "./Projects/Projects";
export { default as Settings } from "./Settings/Settings";
export { default as Team } from "./Team/Team";
export { default as ToWork } from "./ToWork/ToWork";